#
# Makefile for MELFAS MMS400 Touchscreen driver
#

obj-$(CONFIG_ZTEMT_PRESS_TOUCHSCREEN_CYPRESS)  += cyttsp2_ff.o
obj-$(CONFIG_ZTEMT_PRESS_TOUCHSCREEN_CYPRESS)  += cyttsp3_i2c.o cyttsp2_ff_core.o cyttsp3_ff_factory_api.o
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP3_DEVICETREE_SUPPORT)	+= cyttsp3_devtree.o
