#---------------------------PROX SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PROX_PA224)			+= txc_pa224.o
obj-$(CONFIG_NUBIA_SENSORS_PROX_TMD2772)		+= tmd2772.o
#---------------------------RGB SENSOR----------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_RGB_BH1745)			+= rohm_bh1745.o
#---------------------------HALL SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_HALL_DEVICE)  		+= hall_device.o
obj-$(CONFIG_NUBIA_SENSORS_HALL_DEVICE_SINGLE)	+= hall_signle_out.o
#---------------------------PRESSURE_DEVICE ----------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PRESSURE_DEVICE)		+= pressure_device_ndt.o
#------------------------------FP_DEVICE -------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_FP)                  += gf318m_platform/
obj-$(CONFIG_NUBIA_SENSORS_FP)                  += fpc1020_platform/
